# Generated by Django 2.2.6 on 2020-01-19 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=500)),
                ('category_link', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'ArticleCategories',
            },
        ),
        migrations.CreateModel(
            name='articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1000)),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('price', models.TextField()),
                ('link', models.SlugField()),
            ],
            options={
                'verbose_name_plural': 'articles',
            },
        ),
    ]
