# Generated by Django 2.2.6 on 2020-01-19 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sankalp_collection', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleSeries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series_name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=100)),
                ('category_title', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='sankalp_collection.ArticleCategory')),
            ],
        ),
    ]
