# Generated by Django 2.2.6 on 2020-01-21 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sankalp_collection', '0003_articles_series_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlecategory',
            name='category_image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
