# Generated by Django 2.2.6 on 2020-01-22 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sankalp_collection', '0004_articlecategory_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='series_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='sankalp_collection.ArticleCategory'),
        ),
        migrations.DeleteModel(
            name='ArticleSeries',
        ),
    ]
