# Generated by Django 2.2.6 on 2020-01-25 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sankalp_collection', '0006_auto_20200125_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='image2',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='articles',
            name='image3',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='articles',
            name='image4',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
