# Generated by Django 2.2.6 on 2020-01-25 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sankalp_collection', '0007_auto_20200125_1205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='image4',
        ),
    ]
